# Generated by Django 4.2.20 on 2025-05-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatinQR',
            new_name='CreatingQR',
        ),
    ]
