# Generated by Django 4.2.20 on 2025-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatinQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(null=True, upload_to='qr_codes/', verbose_name='qr-codes')),
            ],
        ),
    ]
