# Generated by Django 4.2.20 on 2025-05-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitados', '0002_creatinqr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatinQR',
        ),
    ]
